### ISSUE TITLE
Communication TODO

### ISSUE THREAD

**Issue by jonesnl** [jonesnl/587TermProject#1]
- [x] Rename Comm::board_is_done()
- [x] Make hash table store winner of board
- [x] Send winner to requesting processor
